site_name: GAISHI
site_url: "https://xin-huang.github.io/gaishi"
repo_url: "https://github.com/xin-huang/gaishi"
edit_uri: ""
docs_dir: 'docs'
theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: cyan
    accent: cyan
plugins:
  - search
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
nav:
- Home: 'index.md'
- User Guide:
  - Overview: 'userguide/overview.md'
  - Configuration: 'userguide/configuration.md'
  - Commands:
    - train: 'userguide/train.md'
    - infer: 'userguide/infer.md'
